# Generated by Django 5.2 on 2025-04-27 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despesa',
            name='categoria',
            field=models.CharField(choices=[('LAZER', 'Lazer'), ('CONTAS', 'Contas'), ('MERCADO', 'Mercado'), ('SAUDE', 'Saúde'), ('COMIDA', 'Comida')], default='CONTAS', max_length=20),
        ),
    ]
