# Generated by Django 5.2 on 2025-05-06 11:48

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_despesa_categoria'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='despesa',
            options={'ordering': ['-data', '-created_at'], 'verbose_name': 'Despesa', 'verbose_name_plural': 'Despesas'},
        ),
        migrations.AddField(
            model_name='despesa',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='despesa',
            name='descricao',
            field=models.CharField(default='Desc', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='despesa',
            name='update_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='despesa',
            name='categoria',
            field=models.CharField(choices=[('LAZER', 'Lazer'), ('CONTAS', 'Contas'), ('MERCADO', 'Mercado'), ('SAUDE', 'Saúde'), ('COMIDA', 'Comida'), ('TRANSPORTE', 'Transporte'), ('EDUCACAO', 'Educação'), ('OUTROS', 'Outros')], default='OUTROS', max_length=20),
        ),
        migrations.AlterField(
            model_name='despesa',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
    ]
